In [1]:
import numpy as np

In [2]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.ones((3,3), dtype = bool)
#or 
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
arr = np.arange(10)
np.array([x for x in arr if x%2 != 0])
#better
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [26]:
arr = np.arange(10)
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [30]:
arr = np.arange(10)
out = arr.copy()
out[arr%2==1] = -1
out
## np.where(condition,x,y) 满足condition，输出x，否则输出y
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b),axis = 0)
##
np.vstack([a, b]) #verticall stack: vstack; horizontal stack: hstack
##
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b),axis = 1)
##
np.hstack([a, b]) #verticall stack: vstack; horizontal stack: hstack
##
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [55]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]
#np.repeat：每个元素复制n次； np.tile：整个数组复制n次

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.array([x for x in set(a) if x in set(b)])
##better 交集
np.intersect1d(a,b)
#np.union1d 并集

array([2, 4])

In [86]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b) #返回集合差
#np.setxor1d 返回不同时存在的元素
#np.in1d 返回是否为子集

array([1, 2, 3, 4])

In [101]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.argwhere(a == b).reshape(1,-1)
##
np.where(a == b)

(array([1, 3, 5, 7]),)

In [118]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.intersect1d(np.where(a>=5),np.where(a<=10))]
##
index = np.where((a >= 5) & (a <= 10))
a[index]
##
a[(a>=5) & (a<=10)]
##

array([ 6,  9, 10])

In [120]:
def pair_max(x, y):
    """Get the maximum of two items"""
    out = []
    for i in range(len(x)):
        if x[i] >= y[i]:
            out.append(x[i])
        else:
            out.append(y[i])
    return np.array(out)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [121]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])
#如果一个python函数只能对单个元素进行某种处理操作，经过vectorize 转化之后，能够实现对一个数组进行处理。
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

In [126]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [127]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [151]:
arr = np.arange(9).reshape(3,3)
arr[[2,1,0],:]
##
arr[::-1,:] #array[x:y:-1],从x位开始向前反向取到y（不包含）

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [150]:
arr = np.arange(9).reshape(3,3)
arr[:,[2,1,0]]
##
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [170]:
rand_arr = np.random.rand(5,3)*5+5
##
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
##
rand_arr = np.random.uniform(5,10, size=(5,3))

array([[9.10844439, 6.61608438, 5.33645378],
       [5.43670519, 8.39905226, 5.04644497],
       [6.41917455, 5.76464209, 5.05258584],
       [6.5485684 , 9.04035594, 6.2212307 ],
       [7.09296896, 5.88036329, 5.50339655]])

In [201]:
rand_arr = np.random.random((5,3))
np.round(rand_arr,3)
## np.set_printoptions 可以调整很多print参数
np.set_printoptions(precision=3) 
rand_arr

array([[0.23 , 0.175, 0.926],
       [0.554, 0.716, 0.512],
       [0.356, 0.105, 0.145],
       [0.59 , 0.86 , 0.826],
       [0.518, 0.508, 0.274]])

In [214]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress = True, precision = 6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [2]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [4]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = np.array([row[4] for row in iris_1d])
species[:5]

/Users/yuchenshen/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
feature = np.array([tuple(row)[:4] for row in iris_1d])
feature
## Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

/Users/yuchenshen/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [82]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
sepallength = iris[:,0]
mean = np.mean(sepallength)
median = np.median(sepallength)
sd = np.std(sepallength)

In [91]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
## or 
S = (sepallength - Smin)/sepallength.ptp()  # ptp: peak to peak, max - min
print(S)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [94]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax_score(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

softmax_score(sepallength)

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q=[5, 95])   

array([4.6  , 7.255])

In [49]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

i, j = np.where(iris_2d)
# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan
##
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', nan, b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

In [102]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(np.where(np.isnan(iris_2d[:,0])))
print(np.count_nonzero(np.where(np.isnan(iris_2d[:,0]))))
##
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

(array([ 10,  11,  42,  78, 118, 127]),)
6
Number of missing values: 
 6
Position of missing values: 
 (array([ 10,  11,  42,  78, 118, 127]),)


In [108]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = np.where((iris_2d[:,2]>1.5)&(iris_2d[:,0]<5.0))
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [191]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
condition = np.where(np.isnan(iris_2d))[0]
new = np.delete(iris_2d,condition,axis=0)
np.shape(new)
##
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
np.shape(iris_2d[any_nan_in_row])
##
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

(130, 4)

In [200]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:,0],iris[:,2])[0,1]
##
from scipy.stats.stats import pearsonr  
corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
print(corr)

0.8717541573048712


In [201]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [209]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
condition = np.where(np.isnan(iris_2d))
iris_2d[condition] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 0. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [217]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
uni = np.unique(iris[:,-1],return_counts=True)
print('unique value:', uni)

unique value: (array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([50, 50, 50]))


In [223]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]
# ['small', 'small', 'small', 'small']

['small', 'small', 'small', 'small']

In [242]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
new = np.insert(iris_2d,5,(np.pi*(iris_2d[:,2].astype(float))*((iris_2d[:,0].astype(float))**2))/3, axis = 1)
new[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [253]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# Get the species column
species = iris[:, 4]
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
##
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36]))


In [300]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

new = iris[iris[:,4]== b'Iris-setosa']
petal = np.unique(new[:,2])
sorted(petal.astype(float),reverse=True)[1]
##
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')
# Get the second last value
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [310]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = [('sepallength','object'), ('sepalwidth','object'), ('petallength','object'), ('petalwidth','object'), ('species','object')]
iris = np.genfromtxt(url, delimiter=',', dtype=names)
np.sort(iris) #order='sepallength')

array([(b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'),
       (b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'),
       (b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'),
       (b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'),
       (b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'),
       (b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'),
       (b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'),
       (b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'),
       (b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'),
       (b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'),
       (b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'),
       (b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'),
       (b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'),
       (b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'),
       (b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'),
       (b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'),
       (b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'),
       (b'4.9', b'2.5', b'4

In [311]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Sort by column position 0: SepalLength
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [327]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

uni = np.unique(iris[:,2],return_counts=True)
uni[0][uni[1].argmax()]
##
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'

In [334]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
petal = iris[:,3]
np.argwhere(petal.astype(float)>1.0)[0]

array([50])

In [6]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a<10]=10
a[a>30]=30
print(a)
## 
print(np.clip(a, a_min=10, a_max=30))

## Using np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [28]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.argsort(a)[-5:]
##
np.argpartition(a, len(a)-5)[-5:]

array([18,  7,  3, 10, 15])

In [41]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [46]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays
np.concatenate(array_of_arrays)

##
arr_2d = np.array([a for arr in array_of_arrays for a in arr])
arr_2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)

def one_hot_encoding(x):
    l = np.unique(x)
    return np.array([np.where(l == i, 1, 0).tolist() for i in x])

one_hot_encoding(arr)

##
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

In [85]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)

def create_row_num(arr):
    exist = []
    num = []
    for a in arr:
        if a not in exist:
            count = 0
            exist.append(a)
        num.append(count)
        count += 1
    return num
create_row_num(species_small)

##
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])


['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [88]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)

def create_grnd_num(arr):
    exist = []
    num = []
    count = -1
    for a in arr:
        if a not in exist:
            exist.append(a)
            count += 1
        num.append(count)
    return num
create_grnd_num(species_small)

##
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]

##
output = []
uniqs = np.unique(species_small)

for val in uniqs:  # uniq values in group
    for s in species_small[species_small==val]:  # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0]  # groupid
        output.append(groupid)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [91]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
b = np.argsort(a)
np.argsort(b)

[ 9  4 15  0 17 16 17  8  9  0]


array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

In [99]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
b = a.reshape(1,-1)
b.argsort().argsort().reshape(a.shape)

##
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

In [105]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
np.max(a,axis=1)

##
np.apply_along_axis(np.max, arr=a, axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

In [110]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
m = np.max(a,axis=1)
n = np.min(a,axis=1)
n/m
##
np.apply_along_axis(lambda x:min(x)/max(x), arr = a, axis =1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [115]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

def duplicate(arr):
    exist = []
    out = []
    for x in arr:
        if x not in exist:
            out.append(False)
            exist.append(x)
        else:
            out.append(True)
    return out
duplicate(a)

##
out = np.full(a.shape[0], True)
# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]
# Mark those positions as False
out[unique_positions] = False
out

Array:  [0 0 3 0 2 4 2 2 2 2]


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [120]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

# List comprehension version
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]
##
# For Loop version
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [122]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [126]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr[np.isnan(arr)==False]

array([1., 2., 3., 5., 6., 7.])

In [131]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
sum([(a[i]-b[i])**2 for i in range(len(a))])**(1/2)
##
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [140]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5])

In [143]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
new = np.repeat(b_1d, a_2d.shape[1]).reshape(a_2d.shape[0],a_2d.shape[1])
a_2d - new

##
print(a_2d - b_1d[:,None])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [154]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.argwhere(x==1)[4]
##
np.where(x == 1)[0][n-1]

array([8])

In [169]:
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.astype(datetime)

##
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [175]:
np.random.seed(100)
Z = np.random.randint(10, size=10)
def moving_average(arr,window=3):
    out = []
    start = 0
    for j in range(window,len(arr)+1):
        out.append(np.average(arr[start:j]))
        start += 1
    return out

##
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

moving_average(Z)

##
np.convolve(Z, np.ones(3)/3, mode='valid') 

[6.333333333333333,
 6.0,
 5.666666666666667,
 4.666666666666667,
 3.6666666666666665,
 2.0,
 3.6666666666666665,
 3.0]

In [183]:
np.arange(5,5+3*10,step=3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [184]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
output

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

In [204]:
arr = np.arange(15) 
print(arr)

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
